version: '3.9'

services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"  # Adjust the port if needed
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000  # Adjust the port if needed
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mydatabase
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: e4yX8152tnKg
    hostname: mongodb-server
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: e4yX8152tnKg
      ME_CONFIG_MONGODB_URL: mongodb://admin:e4yX8152tnKg@mongo:27017/

volumes:
  mongodb:
    external: false

#TO RESET
#docker-compose rm -f
#docker-compose pull
#docker-compose up --build -d